package MODEL.POJO;
// Generated Oct 2, 2011 5:46:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Chitietlaptop generated by hbm2java
 */
public class Chitietlaptop  implements java.io.Serializable {


     private String maChiTietLaptop;
     private Sanpham sanpham;
     private String congNgheCpu;
     private String tocDoCpu;
     private String boNhoDem;
     private String fortSizeBus;
     private String hangCpu;
     private String thongTinMotherBoard;
     private String dungLuongRam;
     private String congNgheRam;
     private String busRam;
     private String mucRamToiDa;
     private String dungLuongOcung;
     private String congNgheOcung;
     private String giaoThucKetNoi;
     private String soVongQuay;
     private String kichThuocManHinh;
     private String chuanManHinh;
     private String cardDoHoa;
     private String loaiCard;
     private String dungLuongCard;
     private String cardAmThanh;
     private String chuanAmThanh;
     private String ketNoi;
     private String bluetooth;
     private String camera;
     private String videoOut;
     private String usb;
     private String cardReader;
     private String adapter;
     private String congNghePin;
     private String thoiGianSuDungPin;
     private String thongTinHeDieuHanh;
     private Integer tinhTrang;

    public Chitietlaptop() {
    }

	
    public Chitietlaptop(String maChiTietLaptop) {
        this.maChiTietLaptop = maChiTietLaptop;
    }
    public Chitietlaptop(String maChiTietLaptop, Sanpham sanpham, String congNgheCpu, String tocDoCpu, String boNhoDem, String fortSizeBus, String hangCpu, String thongTinMotherBoard, String dungLuongRam, String congNgheRam, String busRam, String mucRamToiDa, String dungLuongOcung, String congNgheOcung, String giaoThucKetNoi, String soVongQuay, String kichThuocManHinh, String chuanManHinh, String cardDoHoa, String loaiCard, String dungLuongCard, String cardAmThanh, String chuanAmThanh, String ketNoi, String bluetooth, String camera, String videoOut, String usb, String cardReader, String adapter, String congNghePin, String thoiGianSuDungPin, String thongTinHeDieuHanh, Integer tinhTrang) {
       this.maChiTietLaptop = maChiTietLaptop;
       this.sanpham = sanpham;
       this.congNgheCpu = congNgheCpu;
       this.tocDoCpu = tocDoCpu;
       this.boNhoDem = boNhoDem;
       this.fortSizeBus = fortSizeBus;
       this.hangCpu = hangCpu;
       this.thongTinMotherBoard = thongTinMotherBoard;
       this.dungLuongRam = dungLuongRam;
       this.congNgheRam = congNgheRam;
       this.busRam = busRam;
       this.mucRamToiDa = mucRamToiDa;
       this.dungLuongOcung = dungLuongOcung;
       this.congNgheOcung = congNgheOcung;
       this.giaoThucKetNoi = giaoThucKetNoi;
       this.soVongQuay = soVongQuay;
       this.kichThuocManHinh = kichThuocManHinh;
       this.chuanManHinh = chuanManHinh;
       this.cardDoHoa = cardDoHoa;
       this.loaiCard = loaiCard;
       this.dungLuongCard = dungLuongCard;
       this.cardAmThanh = cardAmThanh;
       this.chuanAmThanh = chuanAmThanh;
       this.ketNoi = ketNoi;
       this.bluetooth = bluetooth;
       this.camera = camera;
       this.videoOut = videoOut;
       this.usb = usb;
       this.cardReader = cardReader;
       this.adapter = adapter;
       this.congNghePin = congNghePin;
       this.thoiGianSuDungPin = thoiGianSuDungPin;
       this.thongTinHeDieuHanh = thongTinHeDieuHanh;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaChiTietLaptop() {
        return this.maChiTietLaptop;
    }
    
    public void setMaChiTietLaptop(String maChiTietLaptop) {
        this.maChiTietLaptop = maChiTietLaptop;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public String getCongNgheCpu() {
        return this.congNgheCpu;
    }
    
    public void setCongNgheCpu(String congNgheCpu) {
        this.congNgheCpu = congNgheCpu;
    }
    public String getTocDoCpu() {
        return this.tocDoCpu;
    }
    
    public void setTocDoCpu(String tocDoCpu) {
        this.tocDoCpu = tocDoCpu;
    }
    public String getBoNhoDem() {
        return this.boNhoDem;
    }
    
    public void setBoNhoDem(String boNhoDem) {
        this.boNhoDem = boNhoDem;
    }
    public String getFortSizeBus() {
        return this.fortSizeBus;
    }
    
    public void setFortSizeBus(String fortSizeBus) {
        this.fortSizeBus = fortSizeBus;
    }
    public String getHangCpu() {
        return this.hangCpu;
    }
    
    public void setHangCpu(String hangCpu) {
        this.hangCpu = hangCpu;
    }
    public String getThongTinMotherBoard() {
        return this.thongTinMotherBoard;
    }
    
    public void setThongTinMotherBoard(String thongTinMotherBoard) {
        this.thongTinMotherBoard = thongTinMotherBoard;
    }
    public String getDungLuongRam() {
        return this.dungLuongRam;
    }
    
    public void setDungLuongRam(String dungLuongRam) {
        this.dungLuongRam = dungLuongRam;
    }
    public String getCongNgheRam() {
        return this.congNgheRam;
    }
    
    public void setCongNgheRam(String congNgheRam) {
        this.congNgheRam = congNgheRam;
    }
    public String getBusRam() {
        return this.busRam;
    }
    
    public void setBusRam(String busRam) {
        this.busRam = busRam;
    }
    public String getMucRamToiDa() {
        return this.mucRamToiDa;
    }
    
    public void setMucRamToiDa(String mucRamToiDa) {
        this.mucRamToiDa = mucRamToiDa;
    }
    public String getDungLuongOcung() {
        return this.dungLuongOcung;
    }
    
    public void setDungLuongOcung(String dungLuongOcung) {
        this.dungLuongOcung = dungLuongOcung;
    }
    public String getCongNgheOcung() {
        return this.congNgheOcung;
    }
    
    public void setCongNgheOcung(String congNgheOcung) {
        this.congNgheOcung = congNgheOcung;
    }
    public String getGiaoThucKetNoi() {
        return this.giaoThucKetNoi;
    }
    
    public void setGiaoThucKetNoi(String giaoThucKetNoi) {
        this.giaoThucKetNoi = giaoThucKetNoi;
    }
    public String getSoVongQuay() {
        return this.soVongQuay;
    }
    
    public void setSoVongQuay(String soVongQuay) {
        this.soVongQuay = soVongQuay;
    }
    public String getKichThuocManHinh() {
        return this.kichThuocManHinh;
    }
    
    public void setKichThuocManHinh(String kichThuocManHinh) {
        this.kichThuocManHinh = kichThuocManHinh;
    }
    public String getChuanManHinh() {
        return this.chuanManHinh;
    }
    
    public void setChuanManHinh(String chuanManHinh) {
        this.chuanManHinh = chuanManHinh;
    }
    public String getCardDoHoa() {
        return this.cardDoHoa;
    }
    
    public void setCardDoHoa(String cardDoHoa) {
        this.cardDoHoa = cardDoHoa;
    }
    public String getLoaiCard() {
        return this.loaiCard;
    }
    
    public void setLoaiCard(String loaiCard) {
        this.loaiCard = loaiCard;
    }
    public String getDungLuongCard() {
        return this.dungLuongCard;
    }
    
    public void setDungLuongCard(String dungLuongCard) {
        this.dungLuongCard = dungLuongCard;
    }
    public String getCardAmThanh() {
        return this.cardAmThanh;
    }
    
    public void setCardAmThanh(String cardAmThanh) {
        this.cardAmThanh = cardAmThanh;
    }
    public String getChuanAmThanh() {
        return this.chuanAmThanh;
    }
    
    public void setChuanAmThanh(String chuanAmThanh) {
        this.chuanAmThanh = chuanAmThanh;
    }
    public String getKetNoi() {
        return this.ketNoi;
    }
    
    public void setKetNoi(String ketNoi) {
        this.ketNoi = ketNoi;
    }
    public String getBluetooth() {
        return this.bluetooth;
    }
    
    public void setBluetooth(String bluetooth) {
        this.bluetooth = bluetooth;
    }
    public String getCamera() {
        return this.camera;
    }
    
    public void setCamera(String camera) {
        this.camera = camera;
    }
    public String getVideoOut() {
        return this.videoOut;
    }
    
    public void setVideoOut(String videoOut) {
        this.videoOut = videoOut;
    }
    public String getUsb() {
        return this.usb;
    }
    
    public void setUsb(String usb) {
        this.usb = usb;
    }
    public String getCardReader() {
        return this.cardReader;
    }
    
    public void setCardReader(String cardReader) {
        this.cardReader = cardReader;
    }
    public String getAdapter() {
        return this.adapter;
    }
    
    public void setAdapter(String adapter) {
        this.adapter = adapter;
    }
    public String getCongNghePin() {
        return this.congNghePin;
    }
    
    public void setCongNghePin(String congNghePin) {
        this.congNghePin = congNghePin;
    }
    public String getThoiGianSuDungPin() {
        return this.thoiGianSuDungPin;
    }
    
    public void setThoiGianSuDungPin(String thoiGianSuDungPin) {
        this.thoiGianSuDungPin = thoiGianSuDungPin;
    }
    public String getThongTinHeDieuHanh() {
        return this.thongTinHeDieuHanh;
    }
    
    public void setThongTinHeDieuHanh(String thongTinHeDieuHanh) {
        this.thongTinHeDieuHanh = thongTinHeDieuHanh;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


