package MODEL.POJO;
// Generated Sep 30, 2011 5:07:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Hinhanhcongty generated by hbm2java
 */
public class Hinhanhcongty  implements java.io.Serializable {


     private String maHinhAnhCongTy;
     private Congty congty;
     private String tenHinhAnhCongTy;
     private String duongDan;
     private Integer tinhTrang;

    public Hinhanhcongty() {
    }

	
    public Hinhanhcongty(String maHinhAnhCongTy) {
        this.maHinhAnhCongTy = maHinhAnhCongTy;
    }
    public Hinhanhcongty(String maHinhAnhCongTy, Congty congty, String tenHinhAnhCongTy, String duongDan, Integer tinhTrang) {
       this.maHinhAnhCongTy = maHinhAnhCongTy;
       this.congty = congty;
       this.tenHinhAnhCongTy = tenHinhAnhCongTy;
       this.duongDan = duongDan;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaHinhAnhCongTy() {
        return this.maHinhAnhCongTy;
    }
    
    public void setMaHinhAnhCongTy(String maHinhAnhCongTy) {
        this.maHinhAnhCongTy = maHinhAnhCongTy;
    }
    public Congty getCongty() {
        return this.congty;
    }
    
    public void setCongty(Congty congty) {
        this.congty = congty;
    }
    public String getTenHinhAnhCongTy() {
        return this.tenHinhAnhCongTy;
    }
    
    public void setTenHinhAnhCongTy(String tenHinhAnhCongTy) {
        this.tenHinhAnhCongTy = tenHinhAnhCongTy;
    }
    public String getDuongDan() {
        return this.duongDan;
    }
    
    public void setDuongDan(String duongDan) {
        this.duongDan = duongDan;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


