package MODEL.POJO;
// Generated Sep 30, 2011 5:07:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private String maLoaiSanPham;
     private String tenLoaiSanPham;
     private Integer tinhTrang;
     private Set sanphams = new HashSet(0);

    public Loaisanpham() {
    }

	
    public Loaisanpham(String maLoaiSanPham) {
        this.maLoaiSanPham = maLoaiSanPham;
    }
    public Loaisanpham(String maLoaiSanPham, String tenLoaiSanPham, Integer tinhTrang, Set sanphams) {
       this.maLoaiSanPham = maLoaiSanPham;
       this.tenLoaiSanPham = tenLoaiSanPham;
       this.tinhTrang = tinhTrang;
       this.sanphams = sanphams;
    }
   
    public String getMaLoaiSanPham() {
        return this.maLoaiSanPham;
    }
    
    public void setMaLoaiSanPham(String maLoaiSanPham) {
        this.maLoaiSanPham = maLoaiSanPham;
    }
    public String getTenLoaiSanPham() {
        return this.tenLoaiSanPham;
    }
    
    public void setTenLoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


