package MODEL.POJO;
// Generated Oct 2, 2011 5:46:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Nganhang generated by hbm2java
 */
public class Nganhang  implements java.io.Serializable {


     private String maNganHang;
     private String tenNganHang;
     private String soTaiKhoan;
     private String diaChi;
     private Integer tinhTrang;

    public Nganhang() {
    }

	
    public Nganhang(String maNganHang) {
        this.maNganHang = maNganHang;
    }
    public Nganhang(String maNganHang, String tenNganHang, String soTaiKhoan, String diaChi, Integer tinhTrang) {
       this.maNganHang = maNganHang;
       this.tenNganHang = tenNganHang;
       this.soTaiKhoan = soTaiKhoan;
       this.diaChi = diaChi;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaNganHang() {
        return this.maNganHang;
    }
    
    public void setMaNganHang(String maNganHang) {
        this.maNganHang = maNganHang;
    }
    public String getTenNganHang() {
        return this.tenNganHang;
    }
    
    public void setTenNganHang(String tenNganHang) {
        this.tenNganHang = tenNganHang;
    }
    public String getSoTaiKhoan() {
        return this.soTaiKhoan;
    }
    
    public void setSoTaiKhoan(String soTaiKhoan) {
        this.soTaiKhoan = soTaiKhoan;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


