package POJO;
// Generated Sep 30, 2011 2:20:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donhang generated by hbm2java
 */
public class Donhang  implements java.io.Serializable {


     private String maDonHang;
     private Hinhthucthanhtoan hinhthucthanhtoan;
     private Nguoidung nguoidung;
     private Date ngayDat;
     private Float tongTien;
     private Float giamGia;
     private Float thanhTien;
     private Integer tinhTrang;
     private Set chitietdonhangs = new HashSet(0);

    public Donhang() {
    }

	
    public Donhang(String maDonHang) {
        this.maDonHang = maDonHang;
    }
    public Donhang(String maDonHang, Hinhthucthanhtoan hinhthucthanhtoan, Nguoidung nguoidung, Date ngayDat, Float tongTien, Float giamGia, Float thanhTien, Integer tinhTrang, Set chitietdonhangs) {
       this.maDonHang = maDonHang;
       this.hinhthucthanhtoan = hinhthucthanhtoan;
       this.nguoidung = nguoidung;
       this.ngayDat = ngayDat;
       this.tongTien = tongTien;
       this.giamGia = giamGia;
       this.thanhTien = thanhTien;
       this.tinhTrang = tinhTrang;
       this.chitietdonhangs = chitietdonhangs;
    }
   
    public String getMaDonHang() {
        return this.maDonHang;
    }
    
    public void setMaDonHang(String maDonHang) {
        this.maDonHang = maDonHang;
    }
    public Hinhthucthanhtoan getHinhthucthanhtoan() {
        return this.hinhthucthanhtoan;
    }
    
    public void setHinhthucthanhtoan(Hinhthucthanhtoan hinhthucthanhtoan) {
        this.hinhthucthanhtoan = hinhthucthanhtoan;
    }
    public Nguoidung getNguoidung() {
        return this.nguoidung;
    }
    
    public void setNguoidung(Nguoidung nguoidung) {
        this.nguoidung = nguoidung;
    }
    public Date getNgayDat() {
        return this.ngayDat;
    }
    
    public void setNgayDat(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public Float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Float tongTien) {
        this.tongTien = tongTien;
    }
    public Float getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(Float giamGia) {
        this.giamGia = giamGia;
    }
    public Float getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(Float thanhTien) {
        this.thanhTien = thanhTien;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getChitietdonhangs() {
        return this.chitietdonhangs;
    }
    
    public void setChitietdonhangs(Set chitietdonhangs) {
        this.chitietdonhangs = chitietdonhangs;
    }




}


