package POJO;
// Generated Sep 30, 2011 2:20:10 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hang generated by hbm2java
 */
public class Hang  implements java.io.Serializable {


     private String maHang;
     private String tenHang;
     private Integer tinhTrang;
     private Set sanphams = new HashSet(0);

    public Hang() {
    }

	
    public Hang(String maHang) {
        this.maHang = maHang;
    }
    public Hang(String maHang, String tenHang, Integer tinhTrang, Set sanphams) {
       this.maHang = maHang;
       this.tenHang = tenHang;
       this.tinhTrang = tinhTrang;
       this.sanphams = sanphams;
    }
   
    public String getMaHang() {
        return this.maHang;
    }
    
    public void setMaHang(String maHang) {
        this.maHang = maHang;
    }
    public String getTenHang() {
        return this.tenHang;
    }
    
    public void setTenHang(String tenHang) {
        this.tenHang = tenHang;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


