package MODEL.POJO;
// Generated Oct 13, 2011 8:14:39 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Loainguoidung generated by hbm2java
 */
public class Loainguoidung  implements java.io.Serializable {


     private String maLoaiNguoiDung;
     private String tenLoaiNguoiDung;
     private Integer tinhTrang;
     private Set nguoidungs = new HashSet(0);

    public Loainguoidung() {
    }

	
    public Loainguoidung(String maLoaiNguoiDung) {
        this.maLoaiNguoiDung = maLoaiNguoiDung;
    }
    public Loainguoidung(String maLoaiNguoiDung, String tenLoaiNguoiDung, Integer tinhTrang, Set nguoidungs) {
       this.maLoaiNguoiDung = maLoaiNguoiDung;
       this.tenLoaiNguoiDung = tenLoaiNguoiDung;
       this.tinhTrang = tinhTrang;
       this.nguoidungs = nguoidungs;
    }
   
    public String getMaLoaiNguoiDung() {
        return this.maLoaiNguoiDung;
    }
    
    public void setMaLoaiNguoiDung(String maLoaiNguoiDung) {
        this.maLoaiNguoiDung = maLoaiNguoiDung;
    }
    public String getTenLoaiNguoiDung() {
        return this.tenLoaiNguoiDung;
    }
    
    public void setTenLoaiNguoiDung(String tenLoaiNguoiDung) {
        this.tenLoaiNguoiDung = tenLoaiNguoiDung;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getNguoidungs() {
        return this.nguoidungs;
    }
    
    public void setNguoidungs(Set nguoidungs) {
        this.nguoidungs = nguoidungs;
    }




}


