package MODEL.POJO;
// Generated Oct 13, 2011 8:14:39 AM by Hibernate Tools 3.2.1.GA



/**
 * Sieuthi generated by hbm2java
 */
public class Sieuthi  implements java.io.Serializable {


     private String maSieuThi;
     private Vung vung;
     private String tenSieuThi;
     private String diaChi;
     private Integer tinhTrang;

    public Sieuthi() {
    }

	
    public Sieuthi(String maSieuThi) {
        this.maSieuThi = maSieuThi;
    }
    public Sieuthi(String maSieuThi, Vung vung, String tenSieuThi, String diaChi, Integer tinhTrang) {
       this.maSieuThi = maSieuThi;
       this.vung = vung;
       this.tenSieuThi = tenSieuThi;
       this.diaChi = diaChi;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaSieuThi() {
        return this.maSieuThi;
    }
    
    public void setMaSieuThi(String maSieuThi) {
        this.maSieuThi = maSieuThi;
    }
    public Vung getVung() {
        return this.vung;
    }
    
    public void setVung(Vung vung) {
        this.vung = vung;
    }
    public String getTenSieuThi() {
        return this.tenSieuThi;
    }
    
    public void setTenSieuThi(String tenSieuThi) {
        this.tenSieuThi = tenSieuThi;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


