package MODEL.POJO;
// Generated Sep 30, 2011 4:04:39 PM by Hibernate Tools 3.2.1.GA



/**
 * Chitietdonhang generated by hbm2java
 */
public class Chitietdonhang  implements java.io.Serializable {


     private String maChiTietDonHang;
     private Sanpham sanpham;
     private Donhang donhang;
     private String soLuong;
     private String donGia;
     private String giamGia;
     private String thanhTien;
     private String trangThai;
     private Integer tinhTrang;

    public Chitietdonhang() {
    }

	
    public Chitietdonhang(String maChiTietDonHang) {
        this.maChiTietDonHang = maChiTietDonHang;
    }
    public Chitietdonhang(String maChiTietDonHang, Sanpham sanpham, Donhang donhang, String soLuong, String donGia, String giamGia, String thanhTien, String trangThai, Integer tinhTrang) {
       this.maChiTietDonHang = maChiTietDonHang;
       this.sanpham = sanpham;
       this.donhang = donhang;
       this.soLuong = soLuong;
       this.donGia = donGia;
       this.giamGia = giamGia;
       this.thanhTien = thanhTien;
       this.trangThai = trangThai;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaChiTietDonHang() {
        return this.maChiTietDonHang;
    }
    
    public void setMaChiTietDonHang(String maChiTietDonHang) {
        this.maChiTietDonHang = maChiTietDonHang;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }
    public String getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(String soLuong) {
        this.soLuong = soLuong;
    }
    public String getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(String donGia) {
        this.donGia = donGia;
    }
    public String getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(String giamGia) {
        this.giamGia = giamGia;
    }
    public String getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(String thanhTien) {
        this.thanhTien = thanhTien;
    }
    public String getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


