package MODEL.POJO;
// Generated Oct 4, 2011 11:02:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Congty generated by hbm2java
 */
public class Congty  implements java.io.Serializable {


     private String maCongTy;
     private String tenCongTy;
     private String diaChi;
     private String dienThoai;
     private String hotLine;
     private String email;
     private String website;
     private String gioiThieu;
     private String fax;
     private Set hinhanhcongties = new HashSet(0);

    public Congty() {
    }

	
    public Congty(String maCongTy) {
        this.maCongTy = maCongTy;
    }
    public Congty(String maCongTy, String tenCongTy, String diaChi, String dienThoai, String hotLine, String email, String website, String gioiThieu, String fax, Set hinhanhcongties) {
       this.maCongTy = maCongTy;
       this.tenCongTy = tenCongTy;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.hotLine = hotLine;
       this.email = email;
       this.website = website;
       this.gioiThieu = gioiThieu;
       this.fax = fax;
       this.hinhanhcongties = hinhanhcongties;
    }
   
    public String getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(String maCongTy) {
        this.maCongTy = maCongTy;
    }
    public String getTenCongTy() {
        return this.tenCongTy;
    }
    
    public void setTenCongTy(String tenCongTy) {
        this.tenCongTy = tenCongTy;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getHotLine() {
        return this.hotLine;
    }
    
    public void setHotLine(String hotLine) {
        this.hotLine = hotLine;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(String gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public Set getHinhanhcongties() {
        return this.hinhanhcongties;
    }
    
    public void setHinhanhcongties(Set hinhanhcongties) {
        this.hinhanhcongties = hinhanhcongties;
    }




}


