package MODEL.POJO;
// Generated Sep 30, 2011 4:04:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Khuyenmai generated by hbm2java
 */
public class Khuyenmai  implements java.io.Serializable {


     private String maKhuyenMai;
     private String tenKhuyenMai;
     private String noiDungKhuyenMai;
     private Date ngayBatDau;
     private Date ngayKetThuc;
     private Integer tinhTrang;
     private Set hinhanhkhuyenmais = new HashSet(0);

    public Khuyenmai() {
    }

	
    public Khuyenmai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public Khuyenmai(String maKhuyenMai, String tenKhuyenMai, String noiDungKhuyenMai, Date ngayBatDau, Date ngayKetThuc, Integer tinhTrang, Set hinhanhkhuyenmais) {
       this.maKhuyenMai = maKhuyenMai;
       this.tenKhuyenMai = tenKhuyenMai;
       this.noiDungKhuyenMai = noiDungKhuyenMai;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
       this.tinhTrang = tinhTrang;
       this.hinhanhkhuyenmais = hinhanhkhuyenmais;
    }
   
    public String getMaKhuyenMai() {
        return this.maKhuyenMai;
    }
    
    public void setMaKhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public String getTenKhuyenMai() {
        return this.tenKhuyenMai;
    }
    
    public void setTenKhuyenMai(String tenKhuyenMai) {
        this.tenKhuyenMai = tenKhuyenMai;
    }
    public String getNoiDungKhuyenMai() {
        return this.noiDungKhuyenMai;
    }
    
    public void setNoiDungKhuyenMai(String noiDungKhuyenMai) {
        this.noiDungKhuyenMai = noiDungKhuyenMai;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getHinhanhkhuyenmais() {
        return this.hinhanhkhuyenmais;
    }
    
    public void setHinhanhkhuyenmais(Set hinhanhkhuyenmais) {
        this.hinhanhkhuyenmais = hinhanhkhuyenmais;
    }




}


