package MODEL.POJO;
// Generated Oct 13, 2011 8:14:39 AM by Hibernate Tools 3.2.1.GA



/**
 * Loaisanphamhang generated by hbm2java
 */
public class Loaisanphamhang  implements java.io.Serializable {


     private String maLoaiSanPhamHang;
     private Hang hang;
     private Loaisanpham loaisanpham;

    public Loaisanphamhang() {
    }

	
    public Loaisanphamhang(String maLoaiSanPhamHang) {
        this.maLoaiSanPhamHang = maLoaiSanPhamHang;
    }
    public Loaisanphamhang(String maLoaiSanPhamHang, Hang hang, Loaisanpham loaisanpham) {
       this.maLoaiSanPhamHang = maLoaiSanPhamHang;
       this.hang = hang;
       this.loaisanpham = loaisanpham;
    }
   
    public String getMaLoaiSanPhamHang() {
        return this.maLoaiSanPhamHang;
    }
    
    public void setMaLoaiSanPhamHang(String maLoaiSanPhamHang) {
        this.maLoaiSanPhamHang = maLoaiSanPhamHang;
    }
    public Hang getHang() {
        return this.hang;
    }
    
    public void setHang(Hang hang) {
        this.hang = hang;
    }
    public Loaisanpham getLoaisanpham() {
        return this.loaisanpham;
    }
    
    public void setLoaisanpham(Loaisanpham loaisanpham) {
        this.loaisanpham = loaisanpham;
    }




}


